import type {PortfolioEnvelope} from '../../../../packages/domain/src/types.ts';
import {account} from '../../../../packages/domain/src/accounting.ts';
import {D,usd} from '../../../../packages/domain/src/amounts.ts';
import {ageLabel} from '../../../../packages/domain/src/freshness.ts';
export function PortfolioHero({snapshot,loading,masked,onMask}:{snapshot:PortfolioEnvelope|null;loading:boolean;masked:boolean;onMask:()=>void}){
 const a=account(snapshot?.data??null);const qualify=snapshot?.completeness.state!=='complete'||a.uncertain;
 const total=a.net;const value=masked?'••••••':loading&&!snapshot?.data?'Checking wallet':usd(total);
 return <section className="hero" aria-labelledby="hero-title"><div className="hero-main"><div className="eyebrow">YOUR OWNERSHIP LEDGER</div><div className="hero-label"><h1 id="hero-title">Known net value</h1><button className="text-button" onClick={onMask} aria-label={masked?'Show balances':'Hide balances'}>{masked?'Show':'Hide'}</button></div><div className={`hero-value ${loading?'checking':''}`}>{value}</div><p className="muted">24h change unavailable · No verified history</p><span className={`badge ${qualify?'warning':'good'}`}>{loading?'Checking coverage':qualify?'Partial coverage':'Complete within named scope'}</span><p className="hero-note">{qualify?'Known priced assets minus known debts. Missing liabilities may change this value.':'Only the named checks are complete; unknown protocols may exist.'}</p></div>
 <div className="hero-side"><div className="summary-row"><span>Known assets</span><strong>{masked?'••••':usd(a.assets)}</strong></div><div className="summary-row"><span>Known debt</span><strong className="debt">{masked?'••••':usd(a.debts)}</strong></div><div className="allocation" aria-hidden="true"><span/></div><p className="muted small">Amounts are based on the priced asset set. Rewards are shown separately.</p><div className="metric-grid"><div><strong>{snapshot?.data?.tokens.length??'—'}</strong><span>Token holdings</span></div><div><strong>{snapshot?.data?new Set(snapshot.data.positions.map(p=>p.id)).size:'—'}</strong><span>Positions</span></div><div><strong>{a.unpriced}</strong><span>Unpriced</span></div></div><p className="small muted">{snapshot?ageLabel(snapshot.freshness):'Waiting for observations'}{total!==null&&new D(total).isNegative()?' · Known debt exceeds assets':''}</p></div></section>;
}
