import {useState} from 'react';
import type {TokenBalance} from '../../../../packages/domain/src/types.ts';
import {amount,usd} from '../../../../packages/domain/src/amounts.ts';
import {ageLabel} from '../../../../packages/domain/src/freshness.ts';
import {shortAddress} from '../../../../packages/domain/src/wallet.ts';
function TokenRow({token:t,masked}:{token:TokenBalance;masked:boolean}){
 const [copied,setCopied]=useState('');
 return <details className="token-row"><summary><span className={`asset-icon ${t.spam?'dim':''}`} aria-hidden="true">{t.symbol==='SOL'?'≋':t.symbol.slice(0,1)}</span><span className="asset-name"><strong>{t.name}</strong><span>{t.symbol} <span className="muted">· {t.verification==='verified'?'Identity verified':'Unverified token'}</span></span></span><span className="token-balance"><strong>{masked?'••••':amount(t.rawAmount,t.decimals)}</strong><span>{t.accounts.some(a=>a.frozen)?'Frozen':t.program.includes('Tokenz')?'Token-2022':'Balance'}</span></span><span className="row-value"><strong>{masked?'••••':t.usd.value===null?'Unpriced':usd(t.usd.value)}</strong><span>{t.representedBy?'Counted in staking':'USD value'}</span></span><span className="chevron" aria-hidden="true">⌄</span></summary><div className="detail-grid"><div><h4>Identity & amount</h4><p className="mono">{t.mint}</p><button onClick={async()=>{try{await navigator.clipboard.writeText(t.mint);setCopied('Mint copied');}catch{setCopied('Copy unavailable; select the identifier above.');}}}>Copy mint</button><span role="status" className="small">{copied}</span><p>Raw units: <span className="mono">{masked?'••••':t.rawAmount}</span></p><p>Decimals: {t.decimals}</p><p className="mono">Program: {t.program}</p></div><div><h4>Accounts & restrictions</h4>{t.accounts.map(a=><div key={a.address}><p className="mono" title={a.address}>{shortAddress(a.address)} · {masked?'••••':amount(a.rawAmount,t.decimals)}</p><p>{a.frozen?'Frozen':'Not frozen'} · {a.delegate?`Delegated to ${shortAddress(a.delegate)}`:'No delegate reported'}</p>{a.extensions.length>0&&<p>Extensions: {a.extensions.join(', ')}</p>}{a.extensionData&&<pre>{JSON.stringify(a.extensionData,null,2)}</pre>}</div>)}{t.warnings.map(w=><p className="warning-text" key={w.code}>{w.message}</p>)}</div><div><h4>Source & accounting</h4><p>{t.usd.value===null?'Price unavailable. Ownership remains visible.':`Valuation source: ${t.usd.sourceId} · ${t.usd.confidence}`}</p><p>{ageLabel(t.freshness)}</p>{t.price&&<p>Price: {t.price.sourceId} · {t.price.confidence} · cache age {Math.floor(t.price.cacheAgeMs/1000)}s at response · {t.price.freshness.state}. Fetched {t.price.freshness.fetchedAt}. Observation time unavailable.{t.price.priceChange24h!==null&&` Market price change (24h): ${t.price.priceChange24h}%.`}</p>}<p>{t.representedBy?'Receipt and underlying exposure are counted once in staking.':'Wallet-held amount; a balance does not imply it can be transferred.'}</p></div></div></details>;
}
export function TokenList({tokens,masked}:{tokens:TokenBalance[];masked:boolean}){return <div className="ledger-list">{tokens.map(t=><TokenRow key={t.id} token={t} masked={masked}/>)}</div>;}
