import {describe,it,expect} from 'vitest';
import {createApi} from '../../apps/api/src/index.ts';
import {Orchestrator} from '../../apps/api/src/services/orchestrator.ts';
import {envelopeSchema} from '../../packages/domain/src/schemas.ts';
import {DEMO_ADDRESS} from '../fixtures/scenarios.ts';
import {mockRpc} from '../fixtures/rpc.ts';
const post=(path='/api/v1/portfolio',body:unknown={address:DEMO_ADDRESS},headers:Record<string,string>={})=>new Request(`https://ledger.example${path}`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
describe('API boundary',()=>{
 it('returns typed 503 without configured providers',async()=>{const r=await createApi()(post());expect(r.status).toBe(503);const e=envelopeSchema.parse(await r.json());expect(e.data).toBeNull();expect(e.completeness.state).toBe('unknown');expect(r.headers.get('Cache-Control')).toBe('no-store');});
 it('rejects invalid address, unknown scopes and arbitrary RPC parameters',async()=>{const api=createApi();expect((await api(post(undefined,{address:'no'}))).status).toBe(400);expect((await api(post('/api/v1/portfolio/section',{address:DEMO_ADDRESS,section:'arbitrary'}))).status).toBe(400);expect((await api(post(undefined,{address:DEMO_ADDRESS,url:'http://localhost'}))).status).toBe(400);});
 it('rejects oversized, cross-origin and non-JSON bodies',async()=>{const api=createApi();expect((await api(post(undefined,{address:'a'.repeat(3000)}))).status).toBe(413);expect((await api(post(undefined,undefined,{Origin:'https://evil.example'}))).status).toBe(403);expect((await api(post(undefined,undefined,{'Content-Type':'text/plain'}))).status).toBe(415);});
 it('does not accept client supplied position ownership',async()=>{const r=await createApi()(post('/api/v1/positions/detail',{address:DEMO_ADDRESS,positionId:'made-up-position'}));expect(r.status).toBe(404);});
 it('exposes no arbitrary images or RPC routes',async()=>{const api=createApi();expect((await api(new Request('https://ledger.example/api/v1/assets/https://evil.example'))).status).toBe(404);expect((await api(post('/api/sendTransaction'))).status).toBe(404);});
 it('serves health independently of coverage and sanitized provider status',async()=>{const api=createApi({SOLANA_RPC_URL:'https://rpc.example/secret-key'});expect((await api(new Request('https://ledger.example/api/health'))).status).toBe(200);expect(await (await api(new Request('https://ledger.example/api/v1/providers/status'))).text()).not.toContain('secret-key');});
 it('retains explicit scoped empty success; portfolio remains qualified',async()=>{const api=createApi({SOLANA_RPC_URL:'https://rpc.example',ENABLE_RPC:'true'},mockRpc({zero:true}));const response=await api(post('/api/v1/portfolio/section',{address:DEMO_ADDRESS,section:'core'}));const e=envelopeSchema.parse(await response.json());expect(response.status).toBe(200);expect(e.data).toEqual({tokens:[],positions:[]});expect(e.completeness.state).toBe('complete');const full=envelopeSchema.parse(await (await api(post())).json());expect(full.completeness.state).toBe('partial');});
 it('preserves last good snapshot and observation time on refresh failure',async()=>{let now=100000;let fail=false;const fetcher:typeof fetch=(...args)=>mockRpc(fail?{fail:'getBalance'}:{})(...args);const orchestrator=new Orchestrator({SOLANA_RPC_URL:'https://rpc.example',ENABLE_RPC:'true'},fetcher,()=>now);const first=await orchestrator.read(DEMO_ADDRESS,1,'core');now+=31000;fail=true;const second=await orchestrator.read(DEMO_ADDRESS,2,'core');expect(second.freshness.observedAt).toBe(first.freshness.observedAt);expect(second.freshness.state).toBe('stale');expect(second.data?.tokens.map(t=>({id:t.id,raw:t.rawAmount,freshness:t.freshness}))).toEqual(first.data?.tokens.map(t=>({id:t.id,raw:t.rawAmount,freshness:t.freshness})));expect(second.generation).toBe(2);});
 it('coalesces simultaneous identical requests and scopes identity',async()=>{let calls=0;const fetcher:typeof fetch=(...args)=>{calls++;return mockRpc()(...args);};const o=new Orchestrator({SOLANA_RPC_URL:'https://rpc.example',ENABLE_RPC:'true'},fetcher);const [a,b]=await Promise.all([o.read(DEMO_ADDRESS,1,'core'),o.read(DEMO_ADDRESS,2,'core')]);expect(calls).toBe(4);expect(a.snapshotId).toBe(b.snapshotId);expect(b.generation).toBe(2);});
 it('enforces address budget with retry guidance',async()=>{const api=createApi();let r:Response|undefined;for(let i=0;i<13;i++)r=await api(post());expect(r!.status).toBe(429);expect(r!.headers.get('retry-after')).toBe('60');});
});
